package com.msfg.dashboard.service;

import com.msfg.dashboard.exception.ResourceNotFoundException;
import com.msfg.dashboard.model.entity.ContentItem;
import com.msfg.dashboard.model.entity.PromptTemplate;
import com.msfg.dashboard.repository.ContentItemRepository;
import com.msfg.dashboard.repository.PromptTemplateRepository;
import com.msfg.dashboard.security.SecurityUser;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Service
public class ContentService {

    private final PromptTemplateRepository promptTemplateRepository;
    private final ContentItemRepository contentItemRepository;

    public ContentService(PromptTemplateRepository promptTemplateRepository,
                          ContentItemRepository contentItemRepository) {
        this.promptTemplateRepository = promptTemplateRepository;
        this.contentItemRepository = contentItemRepository;
    }

    // --- Templates ---

    public List<PromptTemplate> findAllTemplates() {
        return promptTemplateRepository.findAll();
    }

    @Transactional
    public PromptTemplate createTemplate(PromptTemplate template) {
        return promptTemplateRepository.save(template);
    }

    @Transactional
    public PromptTemplate updateTemplate(Long id, PromptTemplate updates) {
        PromptTemplate template = promptTemplateRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("PromptTemplate", id));

        if (updates.getName() != null) template.setName(updates.getName());
        if (updates.getPromptText() != null) template.setPromptText(updates.getPromptText());
        if (updates.getPlatform() != null) template.setPlatform(updates.getPlatform());
        if (updates.getCategory() != null) template.setCategory(updates.getCategory());

        return promptTemplateRepository.save(template);
    }

    // --- Content Search ---

    public List<ContentItem> searchContent(String query) {
        if (query != null && !query.isBlank()) {
            return contentItemRepository.findByContentContainingIgnoreCase(query);
        }
        return contentItemRepository.findAll();
    }

    // --- Generate (STUBBED) ---

    public Map<String, Object> generateContent(Map<String, Object> request) {
        String topic = (String) request.getOrDefault("topic", "sample topic");
        String platform = (String) request.getOrDefault("platform", "general");

        return Map.of(
                "id", "generated-" + System.currentTimeMillis(),
                "content", "This is AI-generated content about " + topic + " for " + platform +
                        ". In a production environment, this would be generated by OpenAI.",
                "platform", platform,
                "topic", topic,
                "generatedAt", LocalDateTime.now().toString(),
                "status", "draft",
                "wordCount", 42
        );
    }

    // --- Content Items ---

    public List<ContentItem> findAllItems() {
        return contentItemRepository.findAll();
    }

    @Transactional
    public ContentItem updateItem(Long id, ContentItem updates) {
        ContentItem item = contentItemRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("ContentItem", id));

        if (updates.getContent() != null) item.setContent(updates.getContent());
        if (updates.getStatus() != null) item.setStatus(updates.getStatus());
        if (updates.getPlatform() != null) item.setPlatform(updates.getPlatform());

        return contentItemRepository.save(item);
    }

    @Transactional
    public ContentItem approveItem(Long id) {
        ContentItem item = contentItemRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("ContentItem", id));

        item.setStatus("approved");
        item.setApprovedBy(SecurityUser.current());
        item.setApprovedAt(LocalDateTime.now());

        return contentItemRepository.save(item);
    }

    @Transactional
    public void deleteItem(Long id) {
        ContentItem item = contentItemRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("ContentItem", id));
        contentItemRepository.delete(item);
    }

    // --- Publish (STUBBED) ---

    public Map<String, Object> publishContent(Long id) {
        ContentItem item = contentItemRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("ContentItem", id));

        return Map.of(
                "id", id,
                "status", "published",
                "publishedAt", LocalDateTime.now().toString(),
                "platform", item.getPlatform() != null ? item.getPlatform() : "general",
                "message", "Content published successfully (stubbed)",
                "externalId", "ext-" + System.currentTimeMillis()
        );
    }
}
